# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under infor_ml/resources/*
# and infor_ml/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for infor_ml Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./infor_ml

env:
  DATABRICKS_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  prod:
    concurrency: infor_ml-prod-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t users
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t users
