# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under infor_ml/resources/*
# and infor_ml/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for infor_ml Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./infor_ml

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: infor_ml-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t users
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t users
